variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cache/.cargo
  CARGO_TARGET_DIR: $CI_PROJECT_DIR/.cache/.cargo-target

cache:
  key: "$CI_COMMIT_REF_SLUG-$CI_JOB_NAME"
  paths:
    - .cache

before_script:
  - mkdir -p .cache

build-windows:
  stage: build
  image: registry.gitlab.com/kuviman/dock.rs/windows
  script:
    - cargo build --target x86_64-pc-windows-gnu --release
    - mkdir -p artifacts
    - mv $CARGO_TARGET_DIR/x86_64-pc-windows-gnu/release/lifeshot.exe artifacts
  artifacts:
    expire_in: 1 day
    paths:
      - artifacts

pages:
  stage: deploy
  image: registry.gitlab.com/kuviman/dock.rs/web
  script:
    - cargo web deploy --release
    - mv $CARGO_TARGET_DIR/deploy public
    - mv artifacts/lifeshot.exe public/
  artifacts:
    paths:
      - public
