[package]
name = "lifeshot"
version = "0.1.0"
authors = ["kuviman <kuviman@gmail.com>"]
edition = "2018"

[dependencies]
geng = { git = "https://gitlab.com/kuviman/geng", tag = "v0.1.0" }

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.9"